name: Android CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ "geolite.clash.dev" ]
  pull_request:
    branches: [ "geolite.clash.dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Set variables
      run: |
        echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
      shell: bash

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle clean
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload files to GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file_glob: true
        file: ./app/build/outputs/apk/release/*
        tag: ${{ env.TAG_NAME }}
