name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ "geolite.clash.dev" ]
  pull_request:
    branches: [ "geolite.clash.dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set variables
      run: |
        echo "TAG_NAME=$(date --utc '+%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Update local.properties
      run: |
        sed -i "s/^\(project.version_code\)=.*/\1=${TAG_NAME::-2}/" local.properties
        sed -i "s/^\(project.version_name\)=.*/\1=${TAG_NAME}/" local.properties
        cat local.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle
    - name: Gradle clean
      run: ./gradlew clean
    - name: Build with Gradle
      run: ./gradlew app:assembleRelease

